version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmqsample'
    ports:
        - 5672:5672
        - 15672:15672
    # volumes:
    #     - ./docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #     - ./docker-conf/rabbitmq/log/:/var/log/rabbitmq
    # networks:
    #     - rabbitmq_go_net
    environment:
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
        RABBITMQ_DEFAULT_VHOST: "nguyen"

# networks:
#   rabbitmq_go_net:
#     driver: bridge